### ISSUE TITLE
Getting Error When I start express server 

### ISSUE THREAD

**Issue by emerzonic** [nikolas-haug/Lighthouse#5]
0] module.js:557
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module './codes.json'
[0]     at Function.Module._resolveFilename (module.js:555:15)
[0]     at Function.Module._load (module.js:482:25)
[0]     at Module.require (module.js:604:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (/Users/emersondoyah/Documents/bootCampWorkspace/PROJECTS FOLDER/Lighthouse/server/node_modules/http-errors/node_modules/statuses/index.js:15:13)
[0]     at Module._compile (module.js:660:30)
[0]     at Object.Module._extensions..js (module.js:671:10)
[0]     at Module.load (module.js:573:32)
[0]     at tryModuleLoad (module.js:513:12)
[0]     at Function.Module._load (module.js:505:3)
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by emerzonic** [comment]
I deleted the server node_modules and did a clean npm install  and it went away

**Comment by emerzonic** [comment]
Closed as resolved
