### ISSUE TITLE
Duplicate ID error

### ISSUE THREAD

**Issue by panoptic1** [nikolas-haug/Lighthouse#7]
When committing a new entry to the database, we are able to successfully add a new entry only once. On the second try, we get the following error about a dupicate ID connected to the user. This is strange, because we haven't started connecting user info to the entries yet...
[0] { title: 'Debugging', text: 'Are the bugs gone?' }
[0] { MongoError: E11000 duplicate key error collection: lighthouse_test.entries index: username_1 dup key: { : null }
[0]     at Function.MongoError.create (C:\Users\DELL\Desktop\Lighthouse\server\node_modules\mongodb-core\lib\error.js:49:10)
[0]     at toError (C:\Users\DELL\Desktop\Lighthouse\server\node_modules\mongodb\lib\utils.js:149:22)
[0]     at coll.s.topology.insert (C:\Users\DELL\Desktop\Lighthouse\server\node_modules\mongodb\lib\operations\collection_ops.js:803:39)
[0]     at C:\Users\DELL\Desktop\Lighthouse\server\node_modules\mongodb-core\lib\connection\pool.js:531:18
[0]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0]   name: 'MongoError',
[0]   message: 'E11000 duplicate key error collection: lighthouse_test.entries index: username_1 dup key: { : null }',
[0]   driver: true,
[0]   index: 0,
[0]   code: 11000,
[0]   errmsg: 'E11000 duplicate key error collection: lighthouse_test.entries index: username_1 dup key: { : null }',
[0]   [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by emerzonic** [comment]
var mongoose = require("mongoose"); 
###  Problem line: var passportLocalMongoose = require("passport-local-mongoose");
var EntrySchema = new mongoose.Schema({  
    title: String, 
    text: String,
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }, 
    comments: [{ 
        type: mongoose.Schema.Types.ObjectId, 
        ref: "Comments" }] 
    }); 
###  Problem line:  EntrySchema.plugin(passportLocalMongoose); 
    module.exports = mongoose.model("Entry", EntrySchema);

**Comment by emerzonic** [comment]
It was treating it as a user
